# Generated by Django 3.0.9 on 2023-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_wait',
            field=models.BooleanField(default=False, verbose_name='На ожидании'),
        ),
    ]
